/**
 * Monitor page HTML builder — dark-theme utilization dashboard.
 * Served at GET /monitor. Auto-refreshes every 15s.
 * Shows per-account quota bars, reset countdowns, health scores,
 * rate limits, and fleet-wide summary from /api/utilization.
 */
export function buildMonitorPage() {
    const html = [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '<title>SolidStack · Utilization Monitor</title>',
        '<style>',
        ':root{--bg:#0d0f14;--s:#161920;--s2:#1e2130;--bd:#2a2f45;--tx:#e2e8f0;--mt:#64748b;--gn:#22c55e;--yw:#eab308;--rd:#ef4444;--bl:#3b82f6;--pu:#a855f7;--or:#f97316}',
        '*{box-sizing:border-box;margin:0;padding:0}',
        'body{background:var(--bg);color:var(--tx);font-family:system-ui,sans-serif;font-size:13px;line-height:1.5}',
        'header{padding:13px 20px;background:var(--s);border-bottom:1px solid var(--bd);display:flex;align-items:center;justify-content:space-between}',
        'header h1{font-size:15px;font-weight:700}header h1 span{color:var(--bl)}',
        '.rb{font-size:11px;color:var(--mt);display:flex;align-items:center;gap:6px}',
        '.dot{width:7px;height:7px;border-radius:50%;background:var(--gn);animation:pulse 2s infinite}',
        '@keyframes pulse{0%,100%{opacity:1}50%{opacity:.3}}',
        '.fleet{padding:10px 20px;background:var(--s2);border-bottom:1px solid var(--bd);display:flex;gap:20px;flex-wrap:wrap;align-items:center}',
        '.fs{display:flex;flex-direction:column}.fs .v{font-size:18px;font-weight:700}.fs .l{font-size:10px;color:var(--mt);text-transform:uppercase;letter-spacing:.5px}',
        '.fg .v{color:var(--gn)}.fr .v{color:var(--rd)}.fb .v{color:var(--bl)}.fp .v{color:var(--pu)}.fy .v{color:var(--yw)}',
        '.sep{width:1px;height:28px;background:var(--bd)}',
        'main{padding:16px 20px;display:grid;gap:12px}',
        '.card{background:var(--s);border:1px solid var(--bd);border-radius:10px;overflow:hidden}',
        '.c-ok{border-color:#163028}.c-ex{border-color:#3f1515}.c-pt{border-color:#422006}',
        '.ch{padding:11px 14px;display:flex;align-items:center;gap:10px;background:var(--s2);border-bottom:1px solid var(--bd)}',
        '.av{width:30px;height:30px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:12px;flex-shrink:0}',
        '.em{font-weight:500;flex:1;word-break:break-all}.bgs{display:flex;gap:5px;flex-shrink:0}',
        '.badge{font-size:10px;font-weight:600;padding:2px 7px;border-radius:9px;text-transform:uppercase;letter-spacing:.4px}',
        '.b-pro{background:#7c3aed;color:#e9d5ff}.b-free{background:#065f46;color:#a7f3d0}',
        '.b-ex{background:#450a0a;color:#fca5a5}.b-pt{background:#422006;color:#fdba74}.b-ok{background:#052e16;color:#86efac}.b-dis{background:#1e1e2e;color:var(--mt)}',
        '.cb{padding:12px 14px;display:grid;gap:10px}',
        '.sl{font-size:10px;color:var(--mt);text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px}',
        '.sr{display:flex;gap:7px;flex-wrap:wrap}',
        '.sp{font-size:11px;padding:3px 9px;border-radius:20px;font-weight:500}',
        '.sg{background:#052e16;color:#86efac;border:1px solid #166534}.srd{background:#450a0a;color:#fca5a5;border:1px solid #7f1d1d}',
        '.sy{background:#422006;color:#fdba74;border:1px solid #92400e}.sbl{background:#0c1a40;color:#93c5fd;border:1px solid #1e40af}',
        '.qg{display:grid;grid-template-columns:repeat(auto-fill,minmax(185px,1fr));gap:7px}',
        '.qi{display:flex;flex-direction:column;gap:3px}',
        '.qn{font-size:11px;color:var(--mt);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
        '.qbw{background:#1e2130;border-radius:4px;height:5px;overflow:hidden}',
        '.qb{height:100%;border-radius:4px;transition:width .5s}.qb.h{background:var(--gn)}.qb.m{background:var(--yw)}.qb.lw{background:var(--or)}.qb.z{background:var(--rd)}',
        '.qmeta{font-size:10px;color:var(--mt);display:flex;justify-content:space-between}.qr{color:var(--bl)}',
        '.hrow{display:flex;gap:12px;flex-wrap:wrap}.hs .hv{font-size:14px;font-weight:600}.hs .hl{font-size:10px;color:var(--mt)}',
        '.rll{display:flex;flex-direction:column;gap:4px}',
        '.rli{display:flex;justify-content:space-between;align-items:center;background:#450a0a22;border:1px solid #7f1d1d44;border-radius:5px;padding:4px 9px;font-size:11px}',
        '.rli .rm{color:#fca5a5;font-weight:500}.rli .rr{color:var(--mt)}',
        '.cd{font-variant-numeric:tabular-nums;color:var(--yw);font-weight:600}',
        '.lu{font-size:11px;color:var(--mt)}.none{text-align:center;padding:50px;color:var(--mt)}.err{text-align:center;padding:40px;color:var(--rd)}',
        'footer{padding:10px 20px;color:var(--mt);font-size:11px;text-align:center;border-top:1px solid var(--bd)}a{color:var(--bl);text-decoration:none}',
        '.dist-card{padding:12px 20px;background:var(--s2);border-bottom:1px solid var(--bd);display:flex;flex-direction:column;gap:8px}',
        '.dist-title{font-size:11px;color:var(--mt);text-transform:uppercase;letter-spacing:.5px;font-weight:600;display:flex;justify-content:space-between}',
        '.dist-bar{display:flex;height:12px;border-radius:6px;overflow:hidden;background:#1e2130;border:1px solid var(--bd);width:100%}',
        '.dist-segment{height:100%;transition:width .5s;position:relative;cursor:pointer}',
        '.dist-legend{display:flex;gap:12px;flex-wrap:wrap;font-size:11px}',
        '.dist-legend-item{display:flex;align-items:center;gap:5px}',
        '.dist-legend-color{width:8px;height:8px;border-radius:2px}',
        '</style>',
        '</head>',
        '<body>',
        '<header><h1>SolidStack <span>Utilization Monitor</span></h1>',
        '<div class="rb"><div class="dot"></div><span id="lr">Loading...</span>&nbsp;·&nbsp;Refresh in <span id="cr">15</span>s</div></header>',
        '<div class="fleet" id="fleet"></div>',
        '<div class="dist-card" id="dist-card" style="display:none">',
        '  <div class="dist-title"><span>Prompt Request Distribution</span><span id="dist-total" style="color:var(--bl)">0 total requests</span></div>',
        '  <div class="dist-bar" id="dist-bar"></div>',
        '  <div class="dist-legend" id="dist-legend"></div>',
        '</div>',
        '<div class="dist-card" id="model-card" style="display:flex;margin-top:2px">',
        '  <div class="dist-title"><span>Model Family Traffic</span><span id="model-total" style="color:var(--pu)">-</span></div>',
        '  <div class="dist-legend" id="model-legend"></div>',
        '</div>',
        '<main id="grid"><div class="none">Loading accounts...</div></main>',
        '<div class="dist-card" id="event-card" style="display:flex">',
        '  <div class="dist-title"><span>Recent Persistent Events</span><span id="event-count" style="color:var(--gn)">0 events</span></div>',
        '  <div id="event-feed" style="font-size:11px;display:flex;flex-direction:column;gap:5px;max-height:160px;overflow-y:auto;padding-right:4px"></div>',
        '</div>',
        '<footer>Strategy: <span id="strat">-</span> &nbsp;·&nbsp; <a href="/">&#8592; Dashboard</a> &nbsp;·&nbsp; <a href="/api/utilization">Raw JSON</a></footer>',
        '<script>',
        'var R=15,cd=R;',
        'function fmt(s){if(s==null)return"\\u2014";if(s<60)return s+"s";var m=Math.floor(s/60),r=s%60;return m+"m"+(r>0?" "+r+"s":"")}',
        'function ago(s){if(s==null)return"never";if(s<60)return s+"s ago";if(s<3600)return Math.floor(s/60)+"m ago";return Math.floor(s/3600)+"h ago"}',
        'function bc(p){return p<=5?"z":p<=25?"lw":p<=60?"m":"h"}',
        'function ac(e){var p=["#3b82f6","#8b5cf6","#06b6d4","#10b981","#f59e0b","#ef4444","#ec4899","#a855f7","#84cc16","#f97316"],h=0,i;for(i=0;i<e.length;i++)h=(h*31+e.charCodeAt(i))&0xffff;return p[h%p.length]}',
        'function ini(e){var p=e.split("@")[0].split(/[._-]/);return p.length>=2?(p[0][0]+p[1][0]).toUpperCase():e.slice(0,2).toUpperCase()}',
        'async function setCooldown(email, ms){',
        '  try {',
        '    var r = await fetch("/api/accounts/" + encodeURIComponent(email) + "/cooldown", {',
        '      method: "POST",',
        '      headers: { "Content-Type": "application/json" },',
        '      body: JSON.stringify(ms === 0 ? { clear: true } : { cooldownMs: ms })',
        '    });',
        '    await r.json();',
        '    refresh();',
        '  } catch(e) { alert("Error setting cooldown: " + e.message); }',
        '}',
        'function renderFleet(f){',
        '  document.getElementById("strat").textContent=f.strategy||"?";',
        '  document.getElementById("fleet").innerHTML=',
        '    \'<div class="fs fb"><div class="v">\'+f.total+\'</div><div class="l">Total</div></div>\'+',
        '    \'<div class="sep"></div>\'+',
        '    \'<div class="fs fg"><div class="v">\'+f.free+\'</div><div class="l">Free</div></div>\'+',
        '    \'<div class="fs fp"><div class="v">\'+f.pro+\'</div><div class="l">Pro</div></div>\'+',
        '    \'<div class="sep"></div>\'+',
        '    \'<div class="fs fg"><div class="v">\'+f.geminiAvailable+\'</div><div class="l">Gemini &#10003;</div></div>\'+',
        '    \'<div class="fs fb"><div class="v">\'+f.claudeAvailable+\'</div><div class="l">Claude &#10003;</div></div>\'+',
        '    \'<div class="sep"></div>\'+',
        '    \'<div class="fs \'+( f.fullyExhausted>0?"fr":"fg")+\'"><div class="v">\'+f.fullyExhausted+\'</div><div class="l">Exhausted</div></div>\'+',
        '    \'<div class="fs \'+( f.invalid>0?"fy":"fg")+\'"><div class="v">\'+f.invalid+\'</div><div class="l">Invalid</div></div>\';}',
        'function renderCard(a){',
        '  var c=ac(a.email);',
        '  var tier=a.tier==="pro"?\'<span class="badge b-pro">PRO</span>\':\'<span class="badge b-free">FREE</span>\';',
        '  var sb=!a.enabled?\'<span class="badge b-dis">DISABLED</span>\':',
        '    a.status.fullyExhausted?\'<span class="badge b-ex">EXHAUSTED</span>\':',
        '    (!a.status.geminiAvailable||!a.status.claudeAvailable)?\'<span class="badge b-pt">PARTIAL</span>\':',
        '    \'<span class="badge b-ok">ACTIVE</span>\';',
        '  var cls=a.status.fullyExhausted?"c-ex":(!a.status.geminiAvailable||!a.status.claudeAvailable)?"c-pt":"c-ok";',
        '  var gp=a.status.geminiAvailable?\'<span class="sp sg">&#128994; Gemini</span>\':\'<span class="sp srd">&#128308; Gemini &middot; resets \'+fmt(a.status.nextResetInSec)+\'</span>\';',
        '  var cp=a.status.claudeAvailable?\'<span class="sp sbl">&#128309; Claude</span>\':\'<span class="sp srd">&#128308; Claude &middot; resets \'+fmt(a.status.nextResetInSec)+\'</span>\';',
        '  var kp=a.isCoolingDown?\'<span class="sp sy">&#8987; Cooldown \'+fmt(Math.ceil(a.cooldownMs/1000))+\'</span>\':"";',
        '  var ip=a.isInvalid?\'<span class="sp srd">&#10060; \'+( a.invalidReason||"Invalid")+\'</span>\':"";',
        '  var cdBtns=\'<div style="display:flex;gap:4px;margin-top:6px;align-items:center">\'+',
        '    \'<span style="font-size:10px;color:var(--mt);text-transform:uppercase">Cooldown:</span>\'+',
        '    (a.isCoolingDown?\'<button onclick="setCooldown(\\\'\'+a.email+\'\\\',0)" style="background:#052e16;color:#86efac;border:1px solid #166534;border-radius:4px;padding:2px 6px;cursor:pointer;font-size:10px">Clear</button>\':"")+',
        '    \'<button onclick="setCooldown(\\\'\'+a.email+\'\\\',300000)" style="background:#1e2130;color:var(--tx);border:1px solid var(--bd);border-radius:4px;padding:2px 6px;cursor:pointer;font-size:10px">+5m</button>\'+',
        '    \'<button onclick="setCooldown(\\\'\'+a.email+\'\\\',900000)" style="background:#1e2130;color:var(--tx);border:1px solid var(--bd);border-radius:4px;padding:2px 6px;cursor:pointer;font-size:10px">+15m</button>\'+',
        '    \'</div>\';',
        '  var hh="";',
        '  if(a.health){',
        '    var sc=a.health.score>=70?"var(--gn)":a.health.score>=40?"var(--yw)":"var(--rd)";',
        '    var tc=a.health.hasTokens?"var(--gn)":"var(--rd)";',
        '    var fc=a.health.consecutiveFailures>0?"var(--rd)":"var(--gn)";',
        '    var uc=a.health.isUsable?"var(--gn)":"var(--rd)";',
        '    hh=\'<div><div class="sl">Health Tracker</div><div class="hrow">\'+',
        '      \'<div class="hs"><div class="hv" style="color:\'+sc+\'">\'+( a.health.score!=null?a.health.score:"&mdash;")+\'</div><div class="hl">Score</div></div>\'+',
        '      \'<div class="hs"><div class="hv" style="color:\'+tc+\'">\'+( a.health.tokens!=null?a.health.tokens.toFixed(1):"&mdash;")+"/"+( a.health.maxTokens||"?")+\'</div><div class="hl">Token Bucket</div></div>\'+',
        '      \'<div class="hs"><div class="hv" style="color:\'+fc+\'">\'+a.health.consecutiveFailures+\'</div><div class="hl">Failures</div></div>\'+',
        '      \'<div class="hs"><div class="hv" style="color:\'+uc+\'">\'+( a.health.isUsable?"Yes":"No")+\'</div><div class="hl">Usable</div></div>\'+',
        '      \'</div></div>\';}',
        '  var al=Object.entries(a.rateLimits||{}).filter(function(x){return x[1].isRateLimited});',
        '  var rl="";',
        '  if(al.length>0){',
        '    rl=\'<div><div class="sl">Active Rate Limits</div><div class="rll">\'+',
        '      al.map(function(x){var m=x[0],r=x[1];return\'<div class="rli"><span class="rm">&#128683; \'+m+\'</span><span class="rr">resets in <span class="cd">\'+fmt(r.resetInSec)+\'</span></span></div>\';}).join("")+',
        '      \'</div></div>\';}',
        '  var qe=Object.entries(a.quota||{});',
        '  var qh="";',
        '  if(qe.length>0){',
        '    var bars=qe.map(function(x){',
        '      var m=x[0],q=x[1];',
        '      var p=q.remainingPct!=null?q.remainingPct:0;',
        '      var fd=m.indexOf("claude")>=0?"&#128309;":m.indexOf("gemini")>=0?"&#128994;":"&#9898;";',
        '      var rs=q.exhausted&&q.resetInMin!=null?\'<span class="qr">&#8634; \'+fmt(q.resetInSec)+\'</span>\':',
        '        q.resetTime?\'<span style="color:#334155">\'+new Date(q.resetTime).toLocaleDateString()+\'</span>\':"";',
        '      return\'<div class="qi"><div class="qn" title="\'+m+\'">\'+fd+" "+m+\'</div>\'+',
        '        \'<div class="qbw"><div class="qb \'+bc(p)+\'" style="width:\'+p+\'%"></div></div>\'+',
        '        \'<div class="qmeta"><span>\'+p+\'%</span>\'+rs+\'</div></div>\';}).join("");',
        '    qh=\'<div><div class="sl">Quota per Model</div><div class="qg">\'+bars+\'</div></div>\';}',
        '  return\'<div class="card \'+cls+\'">\'+',
        '    \'<div class="ch">\'+',
        '    \'<div class="av" style="background:\'+c+\'22;color:\'+c+\';border:1.5px solid \'+c+\'44">\'+ini(a.email)+\'</div>\'+',
        '    \'<div class="em">\'+a.email+\'</div>\'+',
        '    \'<div class="bgs">\'+tier+sb+\'</div></div>\'+',
        '    \'<div class="cb">\'+',
        '    \'<div><div class="sl">Status</div><div class="sr">\'+gp+cp+kp+ip+\'</div>\'+cdBtns+\'</div>\'+',
        '    hh+rl+qh+',
        '    \'<div class="lu">Last used: <strong>\'+ago(a.lastUsedAgo)+\'</strong></div>\'+',
        '    \'</div></div>\';}',
        'function renderModelStats(rs){',
        '  var mf = (rs && rs.byModelFamily) || {};',
        '  var gem = (mf.gemini && mf.gemini.total) || 0;',
        '  var cld = (mf.claude && mf.claude.total) || 0;',
        '  var tot = gem + cld;',
        '  document.getElementById("model-total").textContent = tot + " total model requests";',
        '  var legend = document.getElementById("model-legend");',
        '  legend.innerHTML = \'<div class="dist-legend-item"><div class="dist-legend-color" style="background:var(--gn)"></div><span>Gemini: \'+gem+\'</span></div>\'+',
        '                     \'<div class="dist-legend-item"><div class="dist-legend-color" style="background:var(--bl)"></div><span>Claude: \'+cld+\'</span></div>\';',
        '}',
        'function renderEventFeed(events){',
        '  var feed = document.getElementById("event-feed");',
        '  var cnt = document.getElementById("event-count");',
        '  cnt.textContent = (events ? events.length : 0) + " persistent events";',
        '  if (!events || !events.length) {',
        '    feed.innerHTML = \'<div style="color:var(--mt)">No recorded events yet</div>\';',
        '    return;',
        '  }',
        '  feed.innerHTML = events.slice(0, 15).map(function(e){',
        '    var badgeCol = e.type === "429" ? "var(--rd)" : e.type === "disabled" ? "var(--yw)" : "var(--gn)";',
        '    var emailText = e.email ? " &middot; " + e.email : "";',
        '    var timeText = new Date(e.timestamp).toLocaleTimeString();',
        '    return \'<div style="display:flex;gap:8px;align-items:center;background:#1e2130;padding:4px 8px;border-radius:4px">\'+',
        '      \'<span style="background:\'+badgeCol+\'22;color:\'+badgeCol+\';font-weight:700;padding:1px 6px;border-radius:3px;font-size:10px">\'+e.type.toUpperCase()+\'</span>\'+',
        '      \'<span style="flex:1;color:var(--tx)">\'+timeText+emailText+\'</span>\'+',
        '      \'</div>\';',
        '  }).join("");',
        '}',
        'function renderDistribution(rs, accounts){',
        '  var dist = rs.distribution || {};',
        '  var total = rs.totalRequests || 0;',
        '  document.getElementById("dist-total").textContent = total + " total requests";',
        '  var bar = document.getElementById("dist-bar");',
        '  var legend = document.getElementById("dist-legend");',
        '  var card = document.getElementById("dist-card");',
        '  card.style.display = "flex";',
        '  if (total === 0) {',
        '    bar.innerHTML = \'<div style="width:100%;text-align:center;font-size:10px;color:var(--mt);line-height:12px">No requests processed yet</div>\';',
        '    legend.innerHTML = "";',
        '    return;',
        '  }',
        '  var htmlBar = "";',
        '  var htmlLegend = "";',
        '  accounts.forEach(function(a){',
        '    var cnt = dist[a.email] ? dist[a.email].total : 0;',
        '    if (cnt > 0) {',
        '      var pct = ((cnt / total) * 100).toFixed(1);',
        '      var col = ac(a.email);',
        '      htmlBar += \'<div class="dist-segment" style="width:\'+pct+\'%;background:\'+col+\'" title="\'+a.email+\': \'+cnt+\' requests (\'+pct+\'%)\"></div>\';',
        '      htmlLegend += \'<div class="dist-legend-item"><div class="dist-legend-color" style="background:\'+col+\'"></div><span>\'+a.email.split("@")[0]+\' (\'+cnt+\')</span></div>\';',
        '    }',
        '  });',
        '  bar.innerHTML = htmlBar || \'<div style="width:100%;text-align:center;font-size:10px;color:var(--mt);line-height:12px">No requests processed yet</div>\';',
        '  legend.innerHTML = htmlLegend;',
        '}',
        'async function refresh(){',
        '  try{',
        '    var r=await fetch("/api/utilization");',
        '    var d=await r.json();',
        '    if(d.status!=="ok")throw new Error(d.error||"Error");',
        '    renderFleet(d.fleet);',
        '    if(d.routingStats) { renderDistribution(d.routingStats, d.accounts); renderModelStats(d.routingStats); }',
        '    if(d.eventLog) renderEventFeed(d.eventLog);',
        '    var g=document.getElementById("grid");',
        '    if(!d.accounts||!d.accounts.length){g.innerHTML=\'<div class="none">No accounts configured.</div>\';return;}',
        '    var sorted=d.accounts.slice().sort(function(a,b){',
        '      if(a.tier!==b.tier)return a.tier==="free"?-1:1;',
        '      if(a.status.fullyExhausted!==b.status.fullyExhausted)return a.status.fullyExhausted?1:-1;',
        '      return 0;});',
        '    g.innerHTML=sorted.map(renderCard).join("");',
        '    document.getElementById("lr").textContent="Updated "+new Date().toLocaleTimeString();',
        '    cd=R;',
        '  }catch(e){document.getElementById("grid").innerHTML=\'<div class="err">&#9888; \'+e.message+\'</div>\';}}',
        'setInterval(function(){cd=Math.max(0,cd-1);document.getElementById("cr").textContent=cd;if(cd===0)refresh();},1000);',
        'refresh();',
        '<\/script>',
        '</body>',
        '</html>'html>'
    ].join('\n');
    return html;
}
