/**
 * Native Tool Catalog — non-MCP capabilities exposed to the chat agent
 * as first-class, selectable tools, on equal footing with SSmcp's tools.
 *
 * Specializations (categories) exist so the agent — and you, scanning
 * the sidebar — can tell at a glance what class of action a tool is
 * and what confirmation/safety behavior to expect:
 *
 *   ui       - live interface changes; always goes through
 *              ChangeConfirmGate (countdown + Keep) on the frontend,
 *              and is refused server-side too if the zone is protected.
 *   browser  - opens a real Chrome window/profile. Fires immediately,
 *              no confirmation gate (it's a new window, not a live swap).
 *   infra    - proxied straight through to SSmcp's existing 47 tools.
 *              Nothing new here, just merged into one list.
 *
 * GET  /api/tools       -> merged list: native tools + SSmcp tools/list
 * POST /api/tools/call  -> dispatch by name; native tools run locally,
 *                          anything else proxies to SSmcp's mcp-api.
 */

import { spawn } from 'child_process';
import { isProtectedZoneServer } from './protected-zones-server.js';

// Same profile map used by /api/auth/launch-browser — reused here so
// "open chrome profile 13" is a single tool call, not a manual OAuth flow.
const FAMILY_PROFILES = {
    'assistaius@gmail.com': 'Profile 24',
    'adamtechnicalsolutions@gmail.com': 'Profile 19',
    'apps000123000@gmail.com': 'Profile 20',
    'aptsoultuions@gmail.com': 'Profile 21',
    'haliburtonarcher@gmail.com': 'Profile 15',
    'adampps@gmail.com': 'Profile 14',
    // Admin/ops profiles referenced elsewhere in webui/index.js
    'adam@adamassist.com': 'Profile 8',
    'apps@reseller.mysolidstate.ca': 'Profile 13',
    'hub@mysolidstate.ca': 'Profile 10',
};

export const NATIVE_TOOLS = [
    {
        name: 'modify_ui',
        category: 'ui',
        description:
            'Propose a live change to a UI zone. Rendered immediately behind a countdown ' +
            'confirmation (Keep / auto-revert). Refused outright if the zone is protected.',
        inputSchema: {
            type: 'object',
            properties: {
                zoneId: { type: 'string', description: 'Target UI zone identifier' },
                request: { type: 'string', description: 'What to change, in plain language' },
            },
            required: ['zoneId', 'request'],
        },
    },
    {
        name: 'open_chrome_profile',
        category: 'browser',
        description:
            'Open a specific Chrome profile (by number or by email/account it belongs to) ' +
            'at a given URL. Fires immediately — no confirmation needed, it just opens a window.',
        inputSchema: {
            type: 'object',
            properties: {
                profile: { type: 'string', description: 'Profile number, e.g. "13", or an account email' },
                url: { type: 'string', description: 'URL to open in that profile' },
            },
            required: ['profile', 'url'],
        },
    },
];

/**
 * Run a native tool. Returns { ok, result } or { ok: false, error }.
 */
export async function callNativeTool(name, args = {}) {
    switch (name) {
        case 'modify_ui': {
            const { zoneId, request } = args;
            if (!zoneId || !request) {
                return { ok: false, error: 'zoneId and request are required' };
            }
            if (isProtectedZoneServer(zoneId)) {
                return {
                    ok: false,
                    error: `Zone "${zoneId}" is protected (safe mode) — no live swap allowed.`,
                };
            }
            // The actual candidate component is generated by the calling agent/LLM,
            // not by this handler. This just validates and hands back a go-ahead —
            // the frontend is responsible for rendering the result through
            // ChangeConfirmGate, which does its own countdown + logging.
            return {
                ok: true,
                result: { zoneId, request, cleared: true },
            };
        }

        case 'open_chrome_profile': {
            const { profile, url } = args;
            if (!profile || !url) {
                return { ok: false, error: 'profile and url are required' };
            }
            // Accept either a raw profile string ("Profile 13" / "13") or an email
            let profileDirectory = /^\d+$/.test(profile) ? `Profile ${profile}` : profile;
            if (FAMILY_PROFILES[profile]) {
                profileDirectory = FAMILY_PROFILES[profile];
            }
            const args_ = ['-na', 'Google Chrome', '--args', `--profile-directory=${profileDirectory}`, url];
            try {
                spawn('open', args_, { detached: true, stdio: 'ignore' }).unref();
                return { ok: true, result: { profileDirectory, url, launched: true } };
            } catch (err) {
                return { ok: false, error: err.message };
            }
        }

        default:
            return { ok: false, error: `Unknown native tool: ${name}` };
    }
}
